### ISSUE TITLE
Support different themes

### ISSUE THREAD

**Issue by imfaber** [contentacms/contenta_jsonapi#241]
Hi all,

I personally find material_admin a little too funky and I still prefer seven for the admin side.
For the API documentation and other things it is nice though.

I know I can simply enable seven, however I've noticed some libraries defined in contenta_enhancements are applied to any theme regardless.

Am I right thinking that those enhancements were meant for material_admin only and they shouldn't be attached if the current theme is different? 

Many thanks.

**Comment by e0ipso** [comment]
I think @briancwald and @mortenson wanted to include an extra module with UX improvements in Contenta.

Nevertheless I think that they'll be interested in learning about what are the particular things that make you think _I personally find material_admin a little too funky_. Maybe we can improve those.

In any case, there is nothing that ties contenta to an admin theme. You're free to choose your own.

**Comment by mortenson** [comment]
@e0ipso https://www.drupal.org/project/material_admin_support adds things like a floating action button to add content, and some entity browser enhancements, but I don't think it would make the theme feel _less_ funky if someone wants to use Seven. 😄 

I think most of the work for this issue will be finding areas where Contenta assumes Material Admin is used as @imfaber mentions, and making sure styling isn't tied to one admin theme.

**Comment by imfaber** [comment]
@e0ipso As I said I actually like material admin, and BTW @mortenson congrats for the awesome work, but it's just that I prefer something simpler especially for form elements. I'm not even sure if "funky" is the right adjective here.

Maybe it's just a matter of habits and if I forced myself to use it I would eventually love it.
But as you @e0ipso said, nothing ties contenta to a theme therefore styling tweaks shouldn't be always applied.  

@mortenson I've identified only a couple of those areas and I'll raise a pull request soon.

**Comment by e0ipso** [comment]
I'd love to hear the areas where people are struggling. That's an awesome
contribution BTW. I hope it didn't come across as criticism :-P

Please ping me in that pr

**Comment by briancwald** [comment]
@imfaber, I cut an Alpha2 last week that has a number of bug fixes with views (specifically ajax conflicts). If the area you were struggling was views UI, then give that new version a go! aside from that, please report anything you find is weird and I will look into it!

**Comment by hudri** [comment]
I think I'm also in the "little too funky" boat. No sorry, I'm in the "a lot too funky" boat :-( Don't get me wrong, it is really looks pretty to look at, but I need to get work done!

IMHO material design is a poor choice for data/developer centered working and it is a poor choice for desktop browsers. It wastes a ton of screen space, and yet despite all the white space doesn't provide a clear structure to the site. 
The contrast is too low (esp. some of the light grey text) and the font weight is too thin, making it really hard to read (might be less worse on a retina display, but it is a problem for normal office PCs, and is a showstopper for visually impaired people or in bright enviroments).
Design is inconsistent when using Field group module (we're using tabs to structure the form display).
The text format dropdown below formatted text fields is quite disconnected from it's host field to due large whitespace, looks like an independent, self-contained data field.
The edit action in operation links is only visible after an additional click... I already dislike original Drupal's linking of the title to the frontend view (**every single one (!)** of our editors expected the "edit node" page when clicking the title), it's even worse when the edit button is hidden.
Radio buttons are unuseable with visually-hidden labels (see Configuration > Languages, was unable to change default language).

I do really like the sticky node actions though, huge improvement! I also like the colorful buttons. The filter expandable filter above the content list is great.

Adminimal theme also is quite "materialistic", but much more useable.

Please excuse if I sound all negative, it is really a pretty interface for a small personal blog... but it's just wrong for something like Contenta.

**Comment by e0ipso** [comment]
> Please excuse if I sound all negative […] but …

I recommend this read: http://xjmdrupal.org/blog/someone-worked-hard-on-it

-----

You don't need to stay with Contenta's defaults. If you don't agree with the default admin theme you can change it pretty easily.

**Comment by briancwald** [comment]
Thanks for the feedback @hudri - I think you make some fair points overall. Like @e0ipso there are no hard dependencies on the theme - feel free to use what you like.

> IMHO material design is a poor choice for data/developer centered working and it is a poor choice for desktop browsers. It wastes a ton of screen space, and yet despite all the white space doesn't provide a clear structure to the site.

I don't agree here (neither does UX experts in the field) which I spent research time on before determining a design language route. Material Design is used for many dashboards and SaaS products where you are doing administration click and wayfinding tasks. The hard part is that using a theme in Drupal doesn't mean you get to manage all the markup how you would like as many elements to come from the API (like form elements). I am looking at ways to reduce whitespace in certain areas - I agree it is too much - but Drupal uses an insanely small font (terrible for visually impaired). In addition, the admin simply does not work for any small format screens or touch devices. seems odd for a CMS - when a huge % of the overall web uses those devices to create content.

> The contrast is too low

I'd like to know where this is the case. I am using the defined material design palettes and ensured they all have a contrast rating for visually impaired (see: https://material.io/color/#!/?view.left=0&view.right=0). If there are areas below that threshold - then that's a bug and I need to resolve it. 

> The text format dropdown

Fair - the text format markup and how it gets injected via Core is terrible - I need to spend more time in that area. https://github.com/briancwald/material_admin/issues/48

> The edit action in operation links is only visible after an additional click

True - Though this was a debated and conscious decision based on user tested research and industry standards. the clickable link & drop-down button is very poorly scored on user testing and completely unusable for touch users. Does it save some time for power users on desktop - sure slightly - but overall its bad on a whole. In a perfect world, there should be a primary button and a secondary drop-down button - that is not easily solved with the components provided by core - through a custom feature could be developed to do that.

> radio buttons are unusable with visually-hidden labels

That is a bug. I have this solved for checkboxes but apparently, radio buttons are an issue too. I have created an issue. https://github.com/briancwald/material_admin/issues/47

> Please excuse if I sound all negative, it is really a pretty interface for a small personal blog... but it's just wrong for something like Contenta.

Thanks for your thoughts, I have focused mostly on content authoring (which is what Contenta is for!) at this point - since its basically unusable in D8 but I plan to put an extra focus on Administrative power users too.

**Comment by hudri** [comment]
Hi @briancwald ,
regarding low contrast: I'm referring to the combination of small font size, thin font weight and text color #9e9e9e (mostly &lt;label&gt;s), but also other text in #9e9e9e like on Structure > Content types > {Bundle} > Edit > the vertical tabs at the bottom

I guess we are using Contenta quite differently, we are using it very data focused, almost like a PIM/MDM, with 20-40 fields per node, and less as a decoupled CMS backend. When asking my editors about the web interface, I often get "I'd like to upload an Excel" as answer...

**Comment by e0ipso** [comment]
@hudri there's no reason why you would not be able to just upload an Excel with Migrate.

**Comment by briancwald** [comment]
@hudri Thanks for the feedback, I have made a number of changes based on your comments. including fixing the radio buttons in tables with hidden labels, contrast rating for labels, vertical rhythm updates (more to do there) to reduce vertical space.

**Comment by e0ipso** [comment]
@briancwald did you tag an alpha release with those changes?

**Comment by briancwald** [comment]
Yes I just did! ~ 1 hour ago. alpha5

**Comment by e0ipso** [comment]
I'll close this one since the ability to change themes is already there.
