### ISSUE TITLE
Unable to install Contenta via Composer

### ISSUE THREAD

**Issue by mettamatt** [contentacms/contenta_jsonapi#314]
Working on [Tugboat integration](https://tugboat.qa) with Contenta, and I'm unable to get it installed. 

1GB Memory, PHP 7.2.8, composer 1.7.2

```
composer -vvv create-project contentacms/contenta-jsonapi-project contenta --stability dev --no-interaction
```

And the script runs out of memory right around here...

```
Writing /root/.composer/cache/repo/https---repo.packagist.org/provider-drupal$outside-in.json into cache
Downloading http://repo.packagist.org/p/lncd/oauth2%2408e1e5dd1cb486705db26fd2217f4624824f6723539b8231bb182474f055f26b.json
Writing /root/.composer/cache/repo/https---repo.packagist.org/provider-lncd$oauth2.json into cache
Downloading http://repo.packagist.org/p/league/oauth2server%24db7cc29d06780f57866bfc58493216a1ea2776787dbc3bcbddf10558713edecb.json
Writing /root/.composer/cache/repo/https---repo.packagist.org/provider-league$oauth2server.json into cache
Downloading http://repo.packagist.org/p/symfony/expression-language%2406df366ff96b37b7def1b730b98d09bbdbae61d9f4ccf9c78311ec07b1cbf7d9.json
Writing /root/.composer/cache/repo/https---repo.packagist.org/provider-symfony$expression-language.json into cache
Killed
```

**Comment by e0ipso** [comment]
Hello @mettamatt! This is so exciting!!

I need to provide an easier way to do all this. The `scripts` folder aims to do this, but it's not very useful at the moment. I'll work on this.

Composer can be a real memory hog. I don't have an immediate solution other than trying to temporarily upgrade the memory limits.

To be honest, I'm baffled that 1GB is not enough memory to install the composer project. The following command will: `1.` upgrade the available memory to unlimited, `2.` Avoid composer timeouts. Maybe the real problem is a timeout?, and `3.` it will not install dev dependencies nor binaries.

Let's see if that helps you. If it succeeds I'd recommend lowering the memory requirements to see if the solution was either 2 or 3.

```
php -d memory_limit=-1 $(which composer) contentacms/contenta-jsonapi-project contenta --stability dev --no-dev --no-install --no-interaction
```

**Comment by e0ipso** [comment]
@mettamatt also, there is a known issue installing Drupal with `drush` with a missing service. If you run into that [try this](https://github.com/contentacms/contenta_jsonapi/blob/8.x-2.x/scripts/development/build-contenta_jsonapi.sh#L65-L69).

Finally, don't forget to enable [some required modules](https://github.com/contentacms/contenta_jsonapi/blob/8.x-2.x/scripts/development/build-contenta_jsonapi.sh#L77).

**Comment by e0ipso** [comment]
@mettamatt this the build script I'm working on. 

```sh
php -r "readfile('https://raw.githubusercontent.com/contentacms/contenta_jsonapi_project/8.x-1.x/scripts/download.sh');" > download-contentacms.sh
chmod a+x download-contentacms.sh
./download-contentacms.sh
```

**Comment by e0ipso** [comment]
Alright, now it all should be much nicer.

See http://www.contentacms.org/#install on how to download and install easily. Let me know if you still have memory issues.

If you do, please request to reopen this issue.

**Comment by mettamatt** [comment]
Wow. Awesome work. I'm trying it now. 

Initially when I ran `./download-contentacms.sh` I received the following error:

>  ERROR  Missing argument: No destination directory provided.

But then I went back and ran `./download-contentacms.sh contenta`, and supplied a destination directory and it worked as expected.
