### ISSUE TITLE
Upgrade to JSON API 2.x

### ISSUE THREAD

**Issue by e0ipso** [contentacms/contenta_jsonapi#316]
Tasks:

In `contenta_enhancements_node_view_alter` change `jsonapi.entity.to_jsonapi` to `jsonapi_extras.entity.to_jsonapi`

**Comment by wimleers** [comment]
Oh hah, I just wrote exactly the same over at https://www.drupal.org/project/jsonapi/issues/3007823#comment-12824480, where people are seemingly running into the fact that Contenta requires `^2.9` as its requirement, and since `2.10` was released last week, that's now getting installed, and causing problems with Contenta's custom logic it seems.

**Comment by wimleers** [comment]
Created PRs #329 and #330.

**Comment by wimleers** [comment]
This has been obsolete for a while now, even more so since #343.
