### ISSUE TITLE
Add explicit documentation about CORS

### ISSUE THREAD

**Issue by e0ipso** [contentacms/contenta_jsonapi#43]
See the Slack thread.

![slack - drupal 2017-06-12 12-21-55](https://user-images.githubusercontent.com/1140906/27029838-49152e76-4f6a-11e7-9d5e-4a97e7659589.png)

**Comment by dawehner** [comment]
Should we remove the documentation from the readme ? I think its not the worst there, but meh

**Comment by e0ipso** [comment]
We can keep it in both places. I would just want to document the reason why we're shipping with those values and how people need to change them. Does that make sense?

**Comment by dawehner** [comment]
Totally!

Mateu Aguiló Bosch <notifications@github.com> schrieb am Mo., 12. Juni 2017
um 11:45 Uhr:

**Comment by mdonadio** [comment]
I am not sure if restricting to localhost out of the box is the best idea.  I wonder how many people are doing headless-dev just locally; I went straight to a firewalled AWS environment because that's where all of my consumers are.

TBH, I really think this is an upstream issue (ha!) where if `cors.config.enabled == TRUE && in_array('*', cors.config.allowedOrigins` then a warning about a potentially insecure setup (similar to the trusted host setting).

**Comment by e0ipso** [comment]
We are changing this for our demo site. I think we should have prominent documentation on this and show how we do it.

**Comment by e0ipso** [comment]
This was done.
