### ISSUE TITLE
Spread the Open Source ❤️ and get inspiration from Reservoir

### ISSUE THREAD

**Issue by e0ipso** [contentacms/contenta_jsonapi#60]
Reservoir has many great things. Let's list the features that we like from the project and vote on them if we'd like to see them in Contenta CMS.

One feature per comment, please add your own! When you add a feature add both a 👍 and a 👎 so people can vote with a single click. Please add screenshots if applicable.

**Comment by e0ipso** [comment]
The dual-format view of a node in the back-end.

![hello world site-install 2017-06-20 00-51-14](https://user-images.githubusercontent.com/1140906/27309122-a1370776-5552-11e7-91b4-cdacdd9556de.png)

**Comment by e0ipso** [comment]
A 30 sec overview tour.

![content site-install 2017-06-20 00-52-18](https://user-images.githubusercontent.com/1140906/27309151-c3764388-5552-11e7-9ae4-db45ff22001e.png)

**Comment by dawehner** [comment]
Generate an oauth client by default

When you install it, you get a oauth client by default, without any command line vodoo needed: https://github.com/contentacms/contenta_jsonapi/issues/56

**Comment by e0ipso** [comment]
The simplified admin settings (even for user/1).

![content site-install 2017-06-20 00-53-14](https://user-images.githubusercontent.com/1140906/27309182-e2df7942-5552-11e7-918d-2078d7eeda54.png)

**Comment by dawehner** [comment]
Editor/Developer role

When you install it, there is a role for both editors and developers. Make that separation is really helpful, IMHO: https://github.com/contentacms/contenta_jsonapi/issues/57

**Comment by e0ipso** [comment]
* Default demo users: and all the logic that warns you to change it in production.
  * Regrouping the User and Simple OAuth settings in a single page.

![users site-install 2017-06-20 00-54-20](https://user-images.githubusercontent.com/1140906/27309213-07d3d374-5553-11e7-9eda-01446693339e.png)

**Comment by e0ipso** [comment]
OpenAPI & ReDoc. **We already have this in! No need to vote.**

![site-install 2017-06-20 00-58-15](https://user-images.githubusercontent.com/1140906/27309313-8e3334be-5553-11e7-840d-9773187f329a.png)

**Comment by e0ipso** [comment]
Simplified admin/content page without views (and without the features that the view adds).

![content site-install 2017-06-20 00-59-13](https://user-images.githubusercontent.com/1140906/27309347-af9157f8-5553-11e7-94a5-fa9f87a272fd.png)

**Comment by e0ipso** [comment]
Lack of a media library. We have one in Contenta.

![content contenta json api 2017-06-20 01-01-03](https://user-images.githubusercontent.com/1140906/27309431-fcecd644-5553-11e7-9d4e-d71b855cc25f.png)

**Comment by e0ipso** [comment]
Remove UI to change the Appearance and Extend.

Yes, it's redundant with https://github.com/contentacms/contenta_jsonapi/issues/60#issuecomment-309595964 but from the opposite angle.

![content contenta json api 2017-06-20 01-02-55](https://user-images.githubusercontent.com/1140906/27309497-6f4cb448-5554-11e7-9463-c3f4909e4d93.png)

**Comment by e0ipso** [comment]
Contenta has a _Knowledge Hub_. Do you like it?

![tutorials contenta json api 2017-06-20 01-06-23](https://user-images.githubusercontent.com/1140906/27309538-b0c88f50-5554-11e7-8faf-307c8374a0c5.png)

**Comment by e0ipso** [comment]
## Add your suggestion!

**Comment by mortenson** [comment]
If we add default roles, I think that adding shortcut sets per role using https://www.drupal.org/project/shortcutperrole is a better option than simplifying the toolbar. Good permissions + good shortcuts really helps content editor UX.

**Comment by e0ipso** [comment]
https://vimeo.com/222271467 is a good feature overview of Reservoir.

**Comment by justafish** [comment]
For the the dual-format view of a node in the back-end - I really like it, but I think it's a terrible editorial experience so +1 if it goes onto a separate tab and the edit interface is the default.

Most decoupled projects I've worked on don't even provide the rendered node under the "View" tab, so even better I think would be the edit form with a JSON view that could slide in from the side.

**Comment by justafish** [comment]
Moved the above discussion to #61

**Comment by chris-hamper** [comment]
Re: @justafish I like the edit-centric approach on the backend. I'd envision having some other way of viewing the node in a quick and easy way via the actual frontend.

She had mentioned on #Contenta that her past approach was changing the "View" tab to be a link to the node on the frontend. I could see having some sort of plugin system that describes to the backend where the frontend is and how this mapping is done.

Capturing other ideas: open the frontend page in a separate tab / window, which is reused when another node is "View"-ed, or use an iframe approach to show the frontend, possibly with a slide-in drawer or toggle-able split view.

**Comment by justafish** [comment]
@chris-hamper we have this as a simple array in the Drupal settings file on the site screen-capped above (it's also able to fully control the URL structure so there's no need for any URL mapping)

**Comment by wimleers** [comment]
I love that the cross-pollination has already started!

And I love that pretty much all of the ideas of Reservoir appeal to Contenta users :) It almost make me wonder if we should move the `reservoir_ui` module into a separate project? Contenta offers a superset of Reservoir's functionality, so it could quite easily add on its own additional things?

(It took me quite a while to figure out how to generate an OAuth2 public/private key pair by default btw — #56 will benefit from that :) Note that it won't work on all environments though!)

- RE: Knowledge Hub: very useful!
- RE: no Views: I did that because if you can query/filter/sort using JSON API, then there's no more need for REST export views. And hence there's no more need to teach users how to set those up. I can see why you'd want to use `views` but not `views_ui` though: for better/richer listings. But then you need to make sure you don't expose those `view` config entities via JSON API!
- RE: OpenAPI: I see you imported it (yay!), but you haven't fully integrated it yet.
- RE: default roles: Reservoir doesn't use the Shortcut module because its experience is … less than ideal. Also, Reservoir reduces the UI surface so massively, that the 4 navigation links in the toolbar ("Content", "API', "Content modeling" and "Access control") bring you within 1 or 2 clicks of anything you might want to do. So there's far less of a need for the Shortcut module. And it's again one module less. Of course, Contenta should make its own choices. I'm just explaining the rationale I applied!
- RE: Vimeo link: I'm glad you like it! It took FAR too much time.
- RE: dual-format view: _excellent_ point, @justafish! I was totally torn about it too. We decided to ship it like this and refine later based on feedback. I agree it's a bad editorial experience for many/most. OTOH I think that for some it might be pretty interesting to see it like that. I'm interested to hear more about how you think this should work. You say that most of the decoupled projects you've worked on don't even provide the rendered node under the "View" tab. So then what _do_ they show there? A JSON view that could slide in from the side sounds very cool, but how do you ensure it's up-to-date, i.e. in sync with what the user has been writing? Do you save the entity to `TempStore` via AJAX and then use that to generate the "live" JSON view? Created https://github.com/acquia/reservoir/issues/11 for this!

**Comment by wimleers** [comment]
Moved my reply to "dual-format view" to https://github.com/contentacms/contenta_jsonapi/issues/61#issuecomment-310013935.

**Comment by dawehner** [comment]
> (It took me quite a while to figure out how to generate an OAuth2 public/private key pair by default btw — #56 will benefit from that :)

The one thing I'm wondering, is this secure. I guess, but I have no idea

**Comment by e0ipso** [comment]
@wimleers, thanks for the feedback!

> But then you need to make sure you don't expose those view config entities via JSON API!

Agree! See http://dev-contentacms.pantheonsite.io/api

**Comment by e0ipso** [comment]
> RE: OpenAPI: I see you imported it (yay!), but you haven't fully integrated it yet.

#59 Should expose a link to it (or something similar), is that what you mean?

**Comment by e0ipso** [comment]
> Reservoir doesn't use the Shortcut module because its experience is … less than ideal.

Any known gotchas? I haven't used it in a while.

**Comment by e0ipso** [comment]
> RE: Vimeo link: I'm glad you like it! It took FAR too much time.

People underestimate how much effort video content is! <3

**Comment by e0ipso** [comment]
On a general note I have to say that I don't like the idea of the back-end server knowing anything about the front-end implementations. Not even to provide links to node pages:

  - You cannot know, with certainty, about the existence of the front-ends (tricky if it's a public API).
  - The front-end may not have a dedicated view action for that _resource entity_ (only coincidental that resource entities match with entity types). Think about how there is no dedicated page for the _embeddable text_.
  - The front-end can operate via links.
  - …

One of the goals of Contenta is to provide best practices. The fundamental one is that the back-end doesn't know *anything* about the front-end. Not even its existence.

When evaluating these things I always imagine my API going public an someone implementing an Alexa skill (no concept of page or viewport) that I don't know about. It usually puts things in perspective.

**Comment by wimleers** [comment]
> The one thing I'm wondering, is this secure. I guess, but I have no idea

It is and it isn't. This generates a unique key pair per site: not one key pair across all Reservoir sites. That's good. But it doesn't store it in an ideal place, it just stores it in `sys_get_temp_dir()`. I got that idea from `\League\OAuth2\Server\CryptKey::saveKeyToFile()`.

**Comment by wimleers** [comment]
> On a general note I have to say that I don't like the idea of the back-end server knowing anything about the front-end implementations.
I agree in principle, but in practice it's of course very valuable. At least for those sites where the "Content administrator" role is used very actively.

I think it could be configurable: a "content front end mapping URL", which accepts either node ID or node UUID, and then generates a front-end URL. Of course, this assumes that there's a _single_ front end.

So another solution could be to make Reservoir/Contenta alter the `oauth2_client` add/edit form, and allow such a URL to be entered there. Then content administrators would be able to preview the same content in any front end they choose.

**Comment by wimleers** [comment]
Oh and regarding security: that means that https://twitter.com/michaellnorth/status/877202039394230272 _definitely_ does not remotely apply here.

**Comment by dawehner** [comment]
<3

Wim Leers <notifications@github.com> schrieb am Mi., 21. Juni 2017 um
11:26 Uhr:

**Comment by e0ipso** [comment]
Thanks for all the inspiration.
