### ISSUE TITLE
Default Editor View for Nodes

### ISSUE THREAD

**Issue by justafish** [contentacms/contenta_jsonapi#61]
Following on from https://github.com/contentacms/contenta_jsonapi/issues/60#issuecomment-309726962

My preference would be to not show the Node View at all, since rendering on the back-end doesn't really make sense in a decoupled world, and instead have the default tab be Edit. Other tabs can then link to the front-end for that particular node. Here's an example of something in production:

<img width="1335" alt="screen shot 2017-06-20 at 15 09 37" src="https://user-images.githubusercontent.com/345613/27337557-aa6d5584-55ca-11e7-85d2-88107a735311.png">

I do like the JSON view like this:
![hello world site-install 2017-06-20 00-51-14](https://user-images.githubusercontent.com/1140906/27309122-a1370776-5552-11e7-91b4-cdacdd9556de.png)
I would love to see that as a separate tab for users with the developer role.

**Comment by tedbow** [comment]
Yes I like this idea to have the edit form be the default view. I also like the idea to the JSON output on separate tab or at least have it only viewable with some sort of developer permission. Because a lot of users would logging in just to edit/add content

I could still a use case for a view tab. What about before the decoupled app has been developed or when someone is downloading the Contenta for first time and just making practice requests. Or in the case where the decouple application is actually a phone app which you can't show in the browser.

Also there could be users who have permission to view other users content but not edit. They might want to browse the content they don't have permission to edit.

**Comment by prestonso** [comment]
From a usability standpoint, the expectation I would have upon clicking an inactive tab is that the tab would become active and still visible, and the preview would show up underneath the row of tabs. This is because I would expect to be able to toggle back and forth much like the "Write" and "Preview" tabs on this GitHub comment form.

A button would be a much better approach here to signify to the user that you are leaving the admin UI entirely.

**Comment by wimleers** [comment]
Copying what I wrote at https://github.com/contentacms/contenta_jsonapi/issues/60#issuecomment-310013457:

> RE: dual-format view: _excellent_ point, @justafish! I was totally torn about it too. We decided to ship it like this and refine later based on feedback. I agree it's a bad editorial experience for many/most. OTOH I think that for some it might be pretty interesting to see it like that. I'm interested to hear more about how you think this should work. You say that most of the decoupled projects you've worked on don't even provide the rendered node under the "View" tab. So then what _do_ they show there? A JSON view that could slide in from the side sounds very cool, but how do you ensure it's up-to-date, i.e. in sync with what the user has been writing? Do you save the entity to `TempStore` via AJAX and then use that to generate the "live" JSON view? Created https://github.com/acquia/reservoir/issues/11 for this!

**Comment by e0ipso** [comment]
> but how do you ensure it's up-to-date, i.e. in sync with what the user has been writing?

There is a service that takes a loaded entity and serializes it in the JSON API module. You may not need to save it to `TempsStore` to do that. That is unless you want to support relationships via IEF (which I don't think it's your intention).

**Comment by e0ipso** [comment]
This was done.
