### ISSUE TITLE
Design for the front page 

### ISSUE THREAD

**Issue by ckrina** [contentacms/contenta_jsonapi#75]
Here is a first version for the homepage design based on #22 as a starting point. Let's iterate on that.
Here is the source on Figma: https://www.figma.com/file/JPY2wxeDoDXXVrdiJCdmWMFn/Contenta?node-id=75%3A157

![desktop](https://user-images.githubusercontent.com/2225966/27606379-4c1af0f2-5b80-11e7-9fdc-b6ec0053fb7a.png)

**Comment by e0ipso** [comment]
Make sure to post any changes necessary to the content and/or markup in here. I will add it as default content so everyone gets that content on install.

**Comment by joaogarin** [comment]
Cool work! Is the idea to go with something along a more custom theme? or just having the basics of the admin material theme and do little iterations on top?

I think some hand crafted illustrations would be a nice fit, although that requires some effort. I personally like to see things get out a bit of the "standard" when it comes to the design of the page. But that comes with some costs.I hate to say it..but wordpress has some good examples of this in the wordpress.com backend :cry: 

In regards to the functionality I guess I would suggest maybe loosing those "View", "Edit", "Delete" prominent tabs there since I don't think this would be the kind of page you would start editing..thats not the idea. I would instead have the tabs with each of these panels and linked to the corresponding box.

maybe each of the frontend you would use could be displayed differntly? I think that list might get long from all the ideas in the chat;P 

Just some idea from contentul, which is basically contenta (but not open source) and has some really simple UI that goes really straight to the point.

![screen shot 2017-06-27 at 22 11 30](https://user-images.githubusercontent.com/2866604/27610303-b1871d76-5b85-11e7-824d-36b20e08b4c1.png)

**Comment by e0ipso** [comment]
@joaogarin this is actually the _user-facing_ theme (material based), for the help and documentation pages that Drupal will be serving as part of Contenta.

I'd love to have more iterations on the designs and UX (there is something going on already), but we can probably go with this design for now and iterate later. Maybe a separate GH issue with tags to discuss all things UX?

For clarity, this design is for the front page. At this moment the front page does not look great, and it's what people see after installation. Let's fix that ASAP.

Makes sense?

**Comment by joaogarin** [comment]
Yeah totally agree on getting this out and iterate over it! as it is a huge improvement. And yeah I get the idea now that this is not an admin page but the actual frontend for contenta. Still I would consider that "administration".

Totally agree on getting something cool to the users after installing (also during installing) asap! ;) cheers. is anyone working on the installation? I would love to throw some ideas on that. I can sketch something out the next days.

**Comment by e0ipso** [comment]
> Still I would consider that "administration".

👍

**Comment by e0ipso** [comment]
> I would love to throw some ideas on that. I can sketch something out the next days.

😍  that would be amazing.

**Comment by e0ipso** [comment]
We are still far from this design implementation. I consider this one of our current priorities.

**Comment by e0ipso** [comment]
We have a first iteration of this, but we are still far from the beautiful designs.
