### ISSUE TITLE
Explore options for a new slogan / project description

### ISSUE THREAD

**Issue by mrjmd** [contentacms/contenta_jsonapi#97]
The current slogan for the project is "Contenta makes your content happy!"

There has been a concern raised that this isn't very descriptive of exactly what Contenta is, so this issue is a place for us to brainstorm succinct ways of describing the project.

**Comment by dawehner** [comment]
Just some ideas: 

* ## The api first CMS which makes you happy (addressing non Drupal users)
* ## The api first distribution which makes you happy (addressing Drupal users)

**Comment by e0ipso** [comment]
Non-judgemental brainstorming appreciated! We want all your wrong ideas (and the good ones too).

**Comment by e0ipso** [comment]
## Decoupled Best Practices from Back to Front

**Comment by e0ipso** [comment]
## The Content-First Decoupled CMS

**Comment by mrjmd** [comment]
```Contenta gets you going with Decoupled Drupal.```
```Contenta: Home of the community's Decoupled Drupal best practices```

**Comment by e0ipso** [comment]
## Examples in All Fronts

**Comment by yann-yinn** [comment]
I think we should consider **WHO** is the first "audience", and **WHAT** Contenta brings to them.
 
I suggest to first focus on **Drupal community** interested in headless / decoupled site, to be more efficient (easier when we know exactly to who we are talking) and to walk step by step. Convince first the "heart" of our audience and then the others.



So, for Drupal people ( dev or drupal industry)

So, what are we bringing to Drupal ? something like

**A simple, fast and powerful solution to go Drupal Headless**

**Truly headless Drupal site in no times**


and, more general, **not** a drupal-first audience ( think we should NOT go there for now) :
**powerful back office for your favorite front-end**

**Comment by mrjmd** [comment]
```Contenta: API-first simplicity backed by the power and community of Drupal```

**Comment by DavidHernandez** [comment]
I like mrjmd suggestion, maybe I will simplify it to `API-first simplicity backed by Drupal`.

**Comment by yann-yinn** [comment]
`API-first simplicity backed by the community of Drupal`

(like to bring back idea of community / opensource in the game )

**Comment by joaogarin** [comment]
Contenta : Plug and play decoupled CMS

**Comment by e0ipso** [comment]
I want to rescue one @nyl-auster had

## Open Source Content as a Service

**Comment by mrjmd** [comment]
```Contenta: Lowering the barriers to Decoupled Drupal```

**Comment by GustavoMarcante** [comment]
I’m new here, so would be right to jump these lines...
But sometimes the view of an “outsider” might be useful.
Specially to add a point at “WHO is the first ‘audience’, and WHAT Contenta brings to them.”

1) First of all, I don’t know Drupal (yet), so I’m an example that **Contenta CMS can attract people that are not connected (yet) with Drupal**.

2) Even being a computer scientist and programmer a looooong time ago, I prefer not “touching code”. So everything that comes **“out of the box”** sounds very nice.

3) = 1+2. If I wanted something easy or simple I would choose Wordpress or Wix. So, please, I suggest – and ask – don’t say “Contenta is easy” or “Contenta is simple”, as many softwares do (and frustrate us...). It is not! It is easier than making everything by hand, sure. But “easy and simple” is Facebook! I like the approach **"Lowering the barriers"**, is much more honest. Sorry to say, I’m being honest.

4) Java world is very attractive, with contemporary architectures and tools. To whom did not do it yet, I strongly suggest looking [craftercms.org](craftercms.org) and [onehippo.org](onehippo.org), both Open Source. And why I’m not there now? Community! **Community and full open source makes a real difference**. Specially when you don’t work in a software enterprise and you live “far from the capitals”. I had problems, I googled and I found answers! I make a questions and… answers came back! Thats wonderful!

5) Javascript is very attractive. You look for something that looks “on the present” and it is made in Javascript. **Clean, fast, young, lightweight: what you expect for a front-end. But this don’t necessarily gives confidence for a back-end**. For a content repository you look for something that can last, strong, reliable, tested by years, by many people, in many circumstances.

6) In CMSs there are the dinosaurs: Wordpress, Joomla, Typo 3 and… Drupal. I have no doubt that Drupal is the one that made the best “evolutional” choices to be a CMS framework, that created an environment around it. Being a dinosaur can became an advantage exactly by transmitting **confidence**.

7) In my personal opinion, decoupled Drupal is what can make Drupal reach the next generation of CMSs – it is not and will not be possible to feed dozens of channels with dozens of independent projects. And a “PHP-like” front-end is starting to look now like a MS-DOS interface looked for us! But for development and authoring there is no reason not to use it (obviously MUCH better than markup language…). I became very happy with Reservoir initiative and the integration with Contenta – Reservoir as a base for Contenta CMS gives a lot of confidence and Contenta as an “opinionated” CMS reach the “out of the box” and “lowering the barriers” proposals. In other words: even being “decoupled” and “API first” a necessary future, would be better to leave technical characterization for Drupal and Reservoir. If the plan is to reach “not so technical users”, using technical words will not help. Would be nice to express **what does these technical decisions mean in therms of benefits for the user?**

In resume: What attract me (and maybe can attract others) is that
* Contenta CMS offers a base that we can trust to create, keep and organize content and build multiple contemporary channels/heads/front-ends for interaction.
In a few words, could be something like:
* a safe ground to play with multiple contents.

Sorry if I extend me too much, but in general to find “the right few words” is difficult. In my city lived a famous poet that said something like “I write a poem again and again until it looks like being made by chance”...

**Comment by e0ipso** [comment]
> I make a questions and… answers came back! Thats wonderful!

I really think this defines an important aspect of Contenta.

**Comment by e0ipso** [comment]
Wow @GustavoMarcante there's a lot of good avise in there. I can only agree with most of what you say.

**Comment by e0ipso** [comment]
> WHO is the first ‘audience’

I was thinking about multiple audiences, let's see what everyone else thinks:
  - _James:_ The Drupal dev that after +4 years is ready to explore new technologies like React.
  - _Lola:_ CTO of a mid sized company looking to modernize their online experience. She likes to do quick tests of things before doing full research.
  - _Andreas:_ The experienced JS developer who's after a free backend that allows him great content modeling tools unlimited and for free.

**Comment by e0ipso** [comment]
I think we can reach James easier than we can reach Lola and Andreas.

**Comment by e0ipso** [comment]
@GustavoMarcante regarding the tagline, I believe that you'd like to see the concepts of **reliability** and **community backed** in there. Am I correct?

**Comment by yann-yinn** [comment]
@GustavoMarcante thanks a lot for your time, very valuable.
Here are some keywords i noted :
- Drupal is a word that gives **confidence** (probably more than contentful, graphcms and such) since it is here since a long time
- **Community** and **full open source** makes a real difference
- I notices you talked several times of the notion of **channel** , could you elaborate on this ?
- **content repository**
- do not say it **works out of the box** if it does not (causing frustration) !

@e0ipso maybe we could add a "Gustavo" to the personas, because well, he is here, maybe a sign :)  He don't know Drupal and is looking for a good open source CMS to be the content repository with channels for JS front-ends : 

` create content models => get JSON => code frontend => get Help from the community `

**Comment by GustavoMarcante** [comment]
@e0ipso @nyl-auster First of all, thanks for your warm welcome and consideration!
In these days is not so common to find people interested is listening and is obvious that this group is!

@nyl-auster Channels are the "heads" of the decoupled system, different ways to interact with content. A bank can have a website and mobile app, they do not have the same layout or functions or interactions, but your account balance must be the same on both ; )
* In Contenta example, the twitter channel could only show the name of the recipe and a link to the site.
* [Channels in Hippo](https://www.onehippo.org/library/concepts/channels/channel-manager.html)
* [A Drupal video](https://www.youtube.com/watch?v=7WfQ5gVCYhY), maybe you know. 

If you want to add me as a case, it would be an honor!  But not to seem so personal, we could call him Peter ; ) If you want to think about Peter, he is more like Lola, but in a small to medium organization (a school, for example):

Peter is the superuser or admin. He is the one who installs and manage Ubuntu, people accounts, organization site, desktop software and cloud services, like Nextcloud in a Digital Ocean droplet. He can work in the organization or be a permanent advisor or service provider. He don't like coding, but can do installations, configurations, drag and drop, read forums and tutorials, choose and enable modules and themes, follow instructions and things like that. He looks for a CMS that he can manage, as he does with Ubuntu, LibreOffice, Nextcloud, Trello. Defining needs, content types and interactions is a reasonable work, because he knows the people, the organization and their needs. What is not reasonable is to wait literally months for developers for each improvement... And he wants the system to evolve over time. To install Drupal is OK for him and he expects a Drupal-like front end to start, planning in the near future to find front end developers to create new channels for the organization.

He creates the environment for clients and workers:
* Clients / readers uses web browsers, in desktop and mobile, Facebook, Tweeter, WhatsApp, Uber, Google Maps/GPS, Bank app, Netlfix. And they expect the organization can interact with them in multiple channels. But this is not viable! Thats why decoupling and Contenta are necessary. They will interact with Contenta content (subscribe to an event, for example) and they expect something like a javascript web page or a smartphones app (and not a "PHP-like" interface).
* Authors / workers  / employees uses LibreOffice, Nextcloud, Google Calendar, Trello. They need an environment like that to produce. They will use Contenta to read and write content, organize events, select content to make available, and so on. They expect edit once and see the result in multiple channels.

@e0ipso That's why reliability and confidence are important, because if the system breaks, clients and workers will get furious and make him crazy! And the organization depends on him.

Drupal presents himself as a content **_framework_** to develop more than websites, to "deliver the right content to the right person at the right time - on the right device". So, in my point of view, one possible appoach is **Contenta: the CMS upon Drupal (and Reservoir) that gives a secure and pleasant (or friendly) starting point to make content available in multiple channels."**

In this way, Contenta CMS would compare to Magnolia, Hippo, ezPublish or Crafter (not Craft), and not with Drupal.

To make you a little bit crazy, integration with CMIS project (module) would be wonderful too. Imagine to chose not only relational databases, but also Alfresco, Mongo DB or Cassandra as repository for media... Drupal appers in Alfresco site as one of two suggestions of CMS integration:
https://www.alfresco.com/platform/integrating-extending-alfresco

Contenta would be the top open source CMS available...

**Comment by yann-yinn** [comment]
@GustavoMarcante thanks for your feedback, always good to know more about the "who" and the "why" :)

@e0ipso @dawehner @mrjmd @joaogarin we had some great suggestions for a new slogan, why not pick a new one from the suggestions ? Maybe a poll ?
PS : i'm gathering right know all the suggestions in one single post / place

**Comment by yann-yinn** [comment]
A lot of great things in this text from http://www.cmswire.com/web-cms/july-open-source-cms-forecast-drupal-jahia-liferay-more/

Drupal
Drupal has released Contenta CMS, which some users are calling “the decoupled Drupal.”  

> Contenta is a Drupal distribution that provides modern API capabilities out-of-the box with JSON API, which amongst other features allows you to fetch nested resources in one request. It’s a foray into the headless CMS space, and it’s aimed at both Drupal users and non-Drupal users who want to build sites and apps for the omnichannel landscape. Contenta is built to feed content to any JavaScript powered website, an Alexa Skill, or even an in-car user interface.
> 
> You can start with a minimal blank slate, or try out a Contenta demo install which demonstrates how to solve some of the different problems encountered when developing and building in a decoupled situation.

I like : 

`the decoupled Drupal.`

`a Drupal distribution that provides modern API capabilities out-of-the box `

**Comment by yann-yinn** [comment]
Here we are : 

- The api first CMS which makes you happy (addressing non Drupal users)
- The api first distribution which makes you happy (addressing Drupal users)
- Decoupled Best Practices from Back to Front
- Examples in All Fronts
- The Content-First Decoupled CMS
- Contenta gets you going with Decoupled Drupal.
- Contenta: Home of the community's Decoupled Drupal best practices
- Contenta: API-first simplicity backed by the power and community of Drupal
- API-first simplicity backed by the community of Drupal
- API-first backed by Drupal community.
- Contenta : Plug and play decoupled CMS
- Open Source Content as a Service
- Contenta : The decoupled Drupal
- Contenta: Lowering the barriers to Decoupled Drupal
- Contenta ; a Drupal distribution that provides modern API capabilities out-of-the box
- A powerful back-end for your favorite front-end

**Comment by yann-yinn** [comment]
Let's vote here for our favorites ! https://docs.google.com/forms/d/e/1FAIpQLSccFJeZZb6tJ_7ZlEBKfCvKw3fINxWDC97q4ByYlOboSWn8VQ/viewform?usp=sf_link

**Comment by briancwald** [comment]
Slightly outside of the 'content' nomenclature, I think it's worth thinking about API and structure data as a primary indicator, as I feel like content is a subset of what actually is provided here.

- Contenta: Bootstrap for API driven Drupal
- Contenta: Structured backend for API driven applications

**Comment by yann-yinn** [comment]
_edited:  9 july 2017_
Here are the results from **22** responses to the above poll. @briancwald choices where not there because the poll was already submitted with some responses, but we can re-introduce them from now in our available choices. 

_Note: Voters where coming from slack contenta channel or from Drupal people i contacted via PM with twitter / facebook ._

Number of votes per choice, several choices where allowed, 

> 3 - The api first CMS which makes you happy
> 1 - The api first distribution which makes you happy
> 3 - Decoupled Best Practices from Back to Front
> 0 - Examples in All Fronts
> 7 - The Content-First Decoupled CMS
> 3 - Contenta gets you going with Decoupled Drupal
> 2 - Contenta: Home of the community's Decoupled Drupal best practices
> 5 - Contenta: API-first simplicity backed by the power and community of Drupal
> 4 - API-first simplicity backed by the community of Drupal
> 3 - API-first backed by Drupal community
> 6 - Contenta : Plug and play decoupled CMS
> 4 - Open Source Content as a Service
> 8 - Contenta : The decoupled Drupal
> 6 - Contenta: Lowering the barriers to Decoupled Drupal
> 4 - Drupal distribution that provides modern API capabilities out-of-the box
> 4 -A powerful back-end for your favorite front-end

**Comment by yann-yinn** [comment]
edited: 9 july 2017
this are the choices with at least 4 votes : 
- The Content-First Decoupled CMS
- The api first CMS which makes you happy
- Contenta: API-first simplicity backed by the power and community of Drupal
- API-first simplicity backed by the community of Drupal
- Contenta : Plug and play decoupled CMS
- Open Source Content as a Service
- Contenta : The decoupled Drupal
- Contenta: Lowering the barriers to Decoupled Drupal
- Drupal distribution that provides modern API capabilities out-of-the box
- A powerful back-end for your favorite front-end

**Comment by GustavoMarcante** [comment]
One suggestion, compiling what is voted above (feel free to fix my English...):
* **Contenta: Community driven decoupled CMS upon Drupal power.**

In my point of view:
"Open Source" is expressed by "community".
"Out of the box" and "plug and play" are implicit in CMS (remembering that Drupal says it is difficult to start because it is not a CMS, but a framework for CMSs, Contenta would be the "ready" CMS).
"API-First", "API capabilities", "Content as a Service", "back-end / front-end" are technical ways ("how") to express "decoupled", that is more used now (as in CMS Wire text above). An even less technical expression ("what it does" instead of "how it does") would be "multiple channels", because this is the problem the user wants to solve with decoupled CMS (much more than just choose a javascript framework): to feed website + app + facebook + twitter + ... is a nightmare! And will be worst each day. So, it could be (again, feel free to fix my English...):
* **Contenta: Community driven CMS to enable multiple channels upon Drupal power.**

At least for me, an "outsider", the last one is _very_ expressive, links developers to users, is unique, is honest, is technically representative. And suggest happiness by including, inviting all, as "contenta" suggest "happy" or "happiness" in Latin languages.

As I'm not a programmer (anymore), that's how I can contribute...

**Comment by yann-yinn** [comment]
@GustavoMarcante a JavaScript framework is the first reason i need a decoupled cms, so i guess it might be the first reason for some developpers. We want now to use React , Angular, Vue but we need a back-end for them, and other solutions are expensive and always as strong as Drupal.

I know channel is a concern but still dont really get why : my content for mobile is the same than content for the site , am i wrong ? And you want to write tweets directly from the CMS for a specific channel ? Why not using a module that tweet automatically when creating new content for ex ? 

I think i need a very precise example of an issue that leads to channel usage, why can't we just use pick all things from the CMS and let clients choose what they are picking from back-office ?

**Comment by GustavoMarcante** [comment]
@nyl-auster You got the point! Developers want decoupled CMS to choose their preferred front-end framework. What is fair! It is the best solution for the dilemma: front-end moves fast, back-end needs to be stable. In other words, ff your system don't show the data, that is a problem; if it looses your data, that is a catastrophe!

The first question would be: **the target of Contenta is only developers or also users**?

Not only the tag, but the decisions, the functionalities, what will be and will not be offered out-of-the-box -- and, by consequence, if Contenta would be the right choice for non-developers -- depends directly on this definition. What am I doing is provoking this very nice people that is engaged in this very nice project to tell us what are the plans! 

I do not know so much about strategical planning. But in general the tag comes after the discussion of the mission. And the mission comes after a reflection and debate of "what do we want to do". A common way to do it is something like a [SWOT analysis](https://en.wikipedia.org/wiki/SWOT_analysis). In short, what we want to do AND we can do AND some people needs (who?) AND that I can show a better solution than the others.

For example. There is A LOT of decoupled CMSs options (even in Drupal are some initiatives, not so well organized, but are). **Will Contenta be "yet another decoupled CMS"?** What are the points that makes Contenta worthwhile? That is what I tried to put above. In other words:

* Users do not look for decoupled CMSs because they like this or that Javascript framework! Or because they like APIs! These are tools -- and is good that developers can choose their tools. But Decoupled CMSs is a need to organize a each time wider content and display it or interact with it in each time vaster ways - what is being called "channels". Imagine the recipes of Contenta demos. They can be shown in learning-to-cook.com, an e-learning environment made in Angular 2 and linked to Alfresco. Or in myrestaurant.com site, made in Ionic, that runs in a smartphone, that the client can consult to ask for delivery. It is not a "twitter plugin". Is about "I don't know where, or how or to whom this content will be shown."

* But at the same time, you need to start developing the content repository and is good you have a way to expose the Content in this process. That is what CMSs like Hippo, Crafter CMS, ezPublish and other do and is more or less what Dries calls "progressive decoupled" -- use the already working exposing capabilities of Drupal to start, and, when you content repository is mature, you enable sites, applications, TVs, voice interfaces, whatsoever accessing it.

So, what can make Contenta a better choice, in my point of view:

* Being in the shoulders of a giant, Drupal, not so easy to use as Wordpress or Wix and not so beauty and agile as Javascript frameworks, but reliable to take care of the precious content and capable of offering a "progressive decoupled" approach, using something like themes, scaffold and/or bootstrap to expose a general view of the content (test content types, check its accuracy, test views, etc.)

* A very nice, communicative and smart community. That knows not just about "polishing bits", but that developed different tools and systems and is very capable to choose the best non conflicting Drupal strategies, modules (and people) and fulfill the gaps to create a "real" working CMS, not just with "administrative" resources (as Reservoir, and they are important), but with opinions, ONE suggestion for each basic element, like "articles", "events", "products", "forums", "comments", workflow, etc., elements that they probably used in their projects and can put as "out-of-the-box" features of Contenta.

Sorry if I am making you crazy!
But there is "a big world out there" and you have full skills to develop something that is a real need (and can make people really happy).
Or would be something like:
https://www.youtube.com/watch?v=fRoEtGuVmu8

Thanks!

**Comment by e0ipso** [comment]
> I do not know so much about strategical planning. But in general the tag comes after the discussion of the mission

We've been talking a lot lately about the mission of Contenta. For anyone interested there is https://medium.com/@mateu.aguilo.bosch/contenta-makes-your-content-happy-6f76bbe0cdae, https://www.youtube.com/watch?v=gTAvdC3WUOM and https://www.slideshare.net/e0ipso/contenta-makes-your-content-happy

**Comment by e0ipso** [comment]
With regards to the JS framework vs multiple distribution channels argument I feel there is value in both. I have had to develop APIs that need to work on tvOS, alexa, react, iOS, Android, … all with a single API. Having to think of all at the same time has lots of implications.

However I value **a lot** the freedom a decoupled CMS gives you because it lets the developer (the person that will build the thing) to **have fun**. Being passionate about what you do is often discarded. I feel it is one of the key factors in a successful project.

---

All that being said I fell that these are two different topics.

I have a proposal:

  1. @nyl-auster, I'd say that you keep leading the tagline refresh how you had planned initially. I would even consider those choices as closed at this point, but that's up to you. You are leading this and ultimately you will have the voice to change this. This is how we make decisions as an open community.
  2. @GustavoMarcante, I don't know about the rest but I **really** like reading your thoughts on this topic. Would you be up to writing a blog post about _Why Contenta?_. I'm sure we will find some editor to give it a polish (since you expressed your lack of confidence in your English skills in other comments). If you're up to it, we'll publish that article with your name and under the Contenta umbrella.

**Comment by GustavoMarcante** [comment]
@e0ipso Thanks for your confidence, I would be really honored to write as you proposed. But what I can write is what **I do expect** from Contenta (and probably some more people), and **not what Contenta is or might be**.

Just to avoid useless confusion, I'd like to make clear that I'm not writing _against_ any of the ideas or any people -- I'm here because I share the same points. I just want to put a _complementary_ point of view.

Decoupled has two sides (that is just why it is called "decoupled"). I can see many attention to presentation side (front-end development), how to take content from Drupal using API and to show it -- what is fundamental. But to have what to present/interact, it must be somebody who produces content -- the authors users (in the end, there is somebody to interact  with it, the client user, and these two can be the same or not).

What I felt in the slogans initially proposed is that just the first aspect is being considered. That is why I made a central explicit question: the target of Contenta is only (front-end) developers or also (content developers) users? The fact that no answers came back reinforces that it is really not clear in the community. And this is a vital definition for me and might be to other people to choose using Contenta or not.

Trying to be even more clear: **Will Contenta be or could be something like other Drupal distributions, as [OpenSocial](https://www.drupal.org/project/social), [OpenEdu](https://www.drupal.org/project/openedu) **(this one based on Acquia Lightning as Contenta could be on Reservoir)** or [Thunder](https://www.drupal.org/project/thunder) **(that is cited in Contenta docs as a reference)**? Or "just" **(even this being a lot)** a collection of modules and examples to front-end developers? How?**

Note, this is a question, not an affirmation... Do you (community) have an affirmative answer?

In my point of view this definition must came before the slogan, because the slogan depends on it.

**Comment by e0ipso** [comment]
> Just to avoid useless confusion, I'd like to make clear that I'm not writing against any of the ideas or any people

I think that is very clear. Sorry if I made it sound otherwise.

**Comment by e0ipso** [comment]
This is what contenta is:

> Or "just" (even this being a lot) a collection of modules and examples to front-end developers?

See the slide number 3 in the slideshare link above.

**Comment by e0ipso** [comment]
> That is why I made a central explicit question: the target of Contenta is only (front-end) developers or also (content developers) users? The fact that no answers came back reinforces that it is really not clear in the community.

The answer is both. Sorry for bot being clearer before.

**Comment by e0ipso** [comment]
> In my point of view this definition must came before the slogan, because the slogan depends on it.

As mentioned above. We have put a lot of work on that, and made the effort to put this work available to everyone: https://github.com/contentacms/contenta_jsonapi/issues/97#issuecomment-313948816

I consider the part of the _Vision & Mission_ to be done. Everything is open to changes, but for now this is what we all think Contenta should be.

**Comment by GustavoMarcante** [comment]
> _the target of Contenta is only (front-end) developers or also (content developers) users?_
> The answer is both.

Thanks, @e0ipso, for making this clearer.
I was feeling almost like a policeman in a interrogation: "Confess! Confess!" :sunglasses:

Regarding the specific question about the features, I think I will open a new issue not to extend this too much.

**Comment by e0ipso** [comment]
LOL

I actually think your questions are spot on. @GustavoMarcante we have been doing Medium for blog posts. Will that work for you?

**Comment by yann-yinn** [comment]
> @nyl-auster, I'd say that you keep leading the tagline refresh 

feel to small for this big question, but i agree to help things go one step further when i can.

I think we may have to focus on changing "Contenta makes your content happy!" to something better for now; to help people understand what's is actually Contenta CMS.  **We are not choosing a slogan forever and it may change at anytime, it's all about improving a little bit current catchline.** 

Sorry for latest and great suggestions that were not in the poll; but i feel we have enough close suggestions and should consider the best results from poll. Keep in mind this feedback was from Drupal developpers mainly, and a few pure JS developpers :

8 - Contenta : The decoupled Drupal
6 - Contenta : Plug and play decoupled CMS
7 - The Content-First Decoupled CMS
And this variants
5 - Contenta: API-first simplicity backed by the power and community of Drupal
4 - API-first simplicity backed by the community of Drupal
3 - API-first backed by Drupal community

I notice that shorten ones have success, we may keep a short one as a catchline, and a longer one as some kind of explanation.

So we may have for example : 

( this one if for Drupal dev for sure )

> **Contenta : The decoupled Drupal**
>  Drupal distribution that provides modern API capabilities out-of-the box

a more generalist one :
>**The Content-First Decoupled CMS**
>_API-first simplicity backed by the power and community of Drupal_

**Comment by e0ipso** [comment]
@nyl-auster great. Do you want to hold a second round with those 2 options only?

**Comment by yann-yinn** [comment]
Don't know ...a third option (my favourite) would be :

**Contenta : The decoupled Drupal**
_API-first simplicity backed by the power and community of Drupal_

I would prefer a word like "solution" instead of "simplicity", because decoupled is quite hard for now :D 

I have the feeling that first mission of Contenta is helping Drupal to mutate from a monolithic CMS to a decoupled CMS. We are opening the road here, and we are several to work hard on making this happen.

**Comment by GustavoMarcante** [comment]
Now it sounds much better!
To avoid the word "Drupal" twice, I would suggest:

**Contenta: Decoupled CMS with examples**
_API-first efficiency backed by the power and community of Drupal_

or, focusing the accurate target audience (which, in my point of view, would be open source users, already Drupal users or not) and exactly what I would google for:

**Contenta: Open source decoupled CMS**
_API-first Drupal with examples_

**Comment by yann-yinn** [comment]
or :
> **Contenta : Open source decoupled CMS**
> _API-first efficiency backed by the power and community of Drupal_ 

Keep in mind catchline may be use alone , like "the decoupled Drupal". Do you want "Drupal" into the main catchline ?

**Comment by yann-yinn** [comment]
@GustavoMarcante i think we should stick with existing suggestions from poll though, they are good enough and we need limits if we want to go one step further. We may still change one or two words if it feels right, but it takes time to constantly re-evaluates new suggestions. ( and we have feedback on suggestions from poll, small but still valuable )

**Comment by GustavoMarcante** [comment]
@nyl-auster Feel absolutely free to use the suggestion as you think is the best way!
I'm not here to create troubles! :smiley:

As I wrote before, I can not help with code, so the point I can contribute is as an "previous" user, an outsider. I'm just answering what is written [above](https://github.com/contentacms/contenta_jsonapi/issues/97#issuecomment-312663925):

> "We want all your wrong ideas (and the good ones too)."

Slogan, tagline, catchline is the best opportunity to make a reflection about what will be done (plan) and who can benefit for it. And ten days is a very very short time regarding to it. The arguments can be used not just in the slogan itself, but in the decisions, presentations, articles, etc. And if you have a "well target" slogan you will get not less and not more people that what you can benefit. I participated in a process like this just twice -- but were very rich moments. I'm trying to indicate a need, a demand, that Contenta can respond to.

In my point of view -- and is perfect if nobody agrees, maybe I can disagree shortly -- it that Contenta would be the best answer for the Google search: "open source decoupled CMS". And "examples" is what made it unique -- relating to Reservoir, for example (you can change the word, but the idea I think is important).

**Comment by yann-yinn** [comment]
Let's summarize suggestions. Maybe @dawehner @e0ipso @justafish should see now if something here describes well Contenta mission and speak to the early adopters they imagine. I have not really any legitimacy to push things further, just wanted to help gathering alternative ideas to "Contenta makes your content happy"

**catchlines :**

- Contenta : The decoupled Drupal
- Contenta : The content first decoupled CMS
- Contenta : Plug and play decoupled CMS
- Contenta : The open source decoupled CMS*
- Contenta : Bootstrap for API driven Drupal*

We may add as a "sub-tagline" :

- Drupal distribution that gives you modern API capabilities out-of-the box
- API-first simplicity backed by the power and community of Drupal
- The community driven API distribution for Drupal 8 (current twitter account description)

_*were suggested _after_ the poll_

PS : concerning examples, it is for sure a very cool thin , but should it be a part of the tagline itself ?

**Comment by e0ipso** [comment]
http://www.contentacms.org has an updated slogan.
